/**
 * The story mode's words (app/story.js runs it): "The Letters" — you wake one winter night in the cabin with no memory,
 * and find letters you wrote to yourself before the forgetting came, hidden along the ways you used to walk. Twenty
 * chapters, one a season (CONFIG.seasons.days = 10 days each, so 200 story days over five years of weather), each
 * day a line of thought and one to three small tasks that take you everywhere on the islands, some places many
 * times. Flashbacks (placeholder pictures for now) come back on chosen days. The end: you remember your son Tomas,
 * call him on the lighthouse radio, and watch his seaplane land.
 *
 * Tasks are 'type:arg:n' strings, optionally '|own text' (app/story.js TASK_TYPES says what each means):
 *  letter:ID  fire:FIRE_ID  visit:PLACE  add:KIND[,KIND]:n  eat:n  sow:n  sit:sunrise|sunset|cabin  lie  sail:PLACE
 *  sailRound  fly:PLACE  dockPlane:ISLAND  refuel  fuel  chest  sleep:cabin|observatory  telescope  bottle  keepsake
 *  radio:fix|listen|call  wait
 * Letter texts are first drafts (placeholders the author will rewrite); flashback pictures are placeholders: `picture`
 * says what each should show, `image` (a URL) replaces the placeholder once there is one.
 */
export const SON = 'Tomas';

/** The six letters of the fuel can's chest (app/fuelQuest.js): where each lies, its lock's row on the chest, its code. */
export const CODES = [
  { id: 'C1', site: 'meadowHouse', row: 'Windmill', symbol: 'mill', code: [4, 1, 7] },
  { id: 'C2', site: 'palmHouse', row: 'Palm', symbol: 'palm', code: [9, 2, 6] },
  { id: 'C3', site: 'volcanoHouse', row: 'Volcano', symbol: 'volcano', code: [3, 8, 5] },
  { id: 'C4', site: 'marshHouse', row: 'Heron', symbol: 'heron', code: [6, 0, 2] },
  { id: 'C5', site: 'lhDoor', row: 'Lighthouse', symbol: 'lighthouse', code: [7, 7, 1] },
  { id: 'C6', site: 'islet', row: 'Shell', symbol: 'shell', code: [2, 5, 9] },
];
const codeLetter = (c, where, line) => ({ id: c.id, site: c.site, title: `The ${c.row} lock`, code: true,
  text: [`${line}`, `The ${c.row.toLowerCase()} row on the chest by the cabin: <b class="code">${c.code.join(' · ')}</b>`, 'Six letters, six rows. Only all six together lift the lid. I made it hard on purpose. You will see why.'], where });

/** Every letter: id, site (story/sites.js), title, text (paragraphs). */
export const LETTERS = [
  { id: 'L01', site: 'bed', title: 'To whoever wakes here', text: ['If you are reading this, you woke up and nothing was there. No name, no yesterday. I know, because I am you, a little earlier.', 'Do not be afraid. You are safe. This is your cabin and your island. First: the fireplace. It lights without anything, just put your hand to it. Get warm. Then sleep again. The morning is kinder.'] },
  { id: 'L02', site: 'porch', title: 'Small things, every day', text: ['Good morning. You will find letters like this one along the ways I used to walk. I hid them where my feet still remember the path, even when my head does not.', 'A rule I made for us: one small thing at a time. Wood for the fire. Water. Food. A walk. Do the day, then sleep. That is all anyone ever does.'] },
  { id: 'L03', site: 'well', title: 'The well', text: ['The well never freezes all the way. Turn the handle slowly, it squeaks.', 'You used to stand here and count the turns out loud for someone. I can\'t remember who. Maybe you will.'] },
  { id: 'L04', site: 'sunrise', title: 'The sunrise bench', text: ['Sit here one morning. The sun comes up out of the sea, right over the lighthouse rock.', 'I built this bench with somebody\'s help. Two sets of initials are cut underneath. One is mine. The other one has gone soft with rain.'] },
  { id: 'L05', site: 'jettyRoot', title: 'The jetty', text: ['The boat at the end is yours. She is called nothing; we never agreed on a name.', 'In winter, only sail when the wind is gentle. The other thing at the jetty, the seaplane, will not start. That is my doing. Be patient with me.'] },
  { id: 'L06', site: 'stones', title: 'The stone ring', text: ['Nobody knows who stood these stones up. Lie down in the middle and look straight up. The sky gets very big.', 'This is where I used to come to think. It is also where I first noticed I was forgetting words. "Lichen." I had to look it up.'] },
  { id: 'L07', site: 'treehouse', title: 'The treehouse', text: ['Somebody small wanted a house in a tree, so somebody tall built one. The ladder is newer; the first one rotted.', 'There is a mark on the post, at the height of a child. Then another, higher. Then a lot higher.'] },
  { id: 'L08', site: 'fire1', title: 'The fire in the woods', text: ['The woodpile has sticks even in snow. Take ten whenever you pass.', 'I talked here, in the woods, to someone who was not there any more. It helped. You can try it too.'] },
  { id: 'L09', site: 'sunset', title: 'The sunset bench', text: ['The other end of the day. The sun goes into the sea on this side.', 'If you have made it ten days, you are doing better than I feared. Winter will turn. The garden will want you soon.'] },
  { id: 'L10', site: 'garden', title: 'The garden', text: ['Seeds are in the box by the beds. Carrots first, they forgive everything.', 'Beans next to anything makes it grow faster. I learned that from a book. Or from a person. Somebody always said "plant beans, they share".'] },
  { id: 'L11', site: 'cairn', title: 'The islet', text: ['You sailed here. Good. The cairn is old; every stone was carried by someone.', 'I put one stone on top for each year I lived on the island. Count them if you like. It is a lot of years.'] },
  { id: 'L12', site: 'northBeach', title: 'The north beach', text: ['Shells come in on this side after a storm. Collect what you like.', 'There was a storm. A bad one, last autumn. That is the last thing I can still write down clearly. After it, the forgetting got much faster.'] },
  { id: 'L13', site: 'fire2', title: 'The hill fire', text: ['Cook here when the wind is from the south. Fish over a fire is better than anything.', 'Someone used to say I burn everything. They were right.'] },
  { id: 'L14', site: 'cavern', title: 'Under the hill', text: ['Bring the lantern. The caverns go a long way.', 'People painted the walls in the far chamber, long before any of us. They wanted to be remembered too. Everybody does.'] },
  { id: 'L15', site: 'crystal', title: 'The crystal chamber', text: ['When the lantern catches the crystals, the whole room lights up for a moment.', 'Memory is like that now. A flash, and then dark again. Keep the flashes. Write them down if you can. I could not always.'] },
  { id: 'L16', site: 'southBeach', title: 'The south beach', text: ['Pebbles here are round as eggs. Someone used to skip them; seven bounces was the record.', 'Not mine. I never got past four.'] },
  { id: 'L17', site: 'crooked', title: 'The crooked tree', text: ['This tree grew bent from the wind. It did not break. Keep that in mind on bad days.', 'Captain Elias, who lived here before us, carved the star. His bottles still wash up. Read them; he forgot nothing, that old man.'] },
  { id: 'L18', site: 'lhJetty', title: 'The lighthouse', text: ['You sailed to the lighthouse. Climb to the top: you can see every island from up there.', 'The keeper\'s room has a table and an old log book. Somewhere in this lighthouse there used to be a radio. It is broken. Leave it for now.'] },
  { id: 'L19', site: 'meadowJetty', title: 'Millholm', text: ['The windmill island. Sheep, stone walls, wind.', 'The miller is long gone, the windmill still turns. I come here when I want to hear something work properly.'] },
  { id: 'L20', site: 'meadowFire', title: 'The Millholm fire', text: ['Warm your hands here. The walls keep the wind off.', 'There was a summer we camped on this island. A tent, a kettle, a boy who would not sleep because the sheep "were looking at him".'] },
  { id: 'L21', site: 'bridge', title: 'The footbridge', text: ['Every plank has been replaced at least once. It is still the same bridge. I think about that a lot.', 'If all your memories are new, are you still the same person? The bridge says yes.'] },
  { id: 'L22', site: 'palmJetty', title: 'Palm Cay', text: ['White sand, warm water, the hut on stilts.', 'This was the holiday island. We pretended it was far away, in the south seas. It is forty minutes by boat.'] },
  { id: 'L23', site: 'palmSide', title: 'Looking west', text: ['From here you can see nothing but sea. Good place for courage.', 'I was not brave about everything. There is someone I should have called a long time ago. I keep putting it off. Do not put it off.'] },
  { id: 'L24', site: 'apple', title: 'The chest with six dials', text: ['By the cabin there is a chest with six rows of dials. The fuel for the seaplane is inside.', 'I locked it and hid the six codes, one on each island and rock, so that only a version of me who can get to all of them, steadily, will fly. A plane is not a boat. Find all six. Then fly.'] },
  { id: 'L25', site: 'marshJetty', title: 'Heron Marsh', text: ['The biggest island and the quietest. Herons stand in the pools like old men waiting for a bus.', 'The lodge on stilts belonged to a fisherman friend. He left me the key. It is not locked anyway.'] },
  { id: 'L26', site: 'volcanoJetty', title: 'Ember Rock', text: ['Black rock, warm ground, the observatory on top. The path zigzags; take it slowly.', 'Do not touch the glowing creek. I should not need to write that, but I am writing for a version of me who forgets things.'] },
  { id: 'L27', site: 'meadowFar', title: 'From the air', text: ['You flew here. From above, the islands look like a family sitting round a table.', 'Five islands and a rock. We counted them once, from this very spot, and argued about whether the islet counts. It does.'] },
  { id: 'L28', site: 'palmFar', title: 'The far beach', text: ['The water here is the colour of a glass bottle held to the sun.', 'A boy learned to swim here. He swallowed half the sea and came up laughing.'] },
  { id: 'L29', site: 'marshFar', title: 'The pools', text: ['Walk carefully, the ground is soft.', 'I wrote this one a long time before the others. My handwriting was steadier. Can you tell?'] },
  { id: 'L30', site: 'emberSpring', title: 'The hot spring', text: ['Warm water out of the rock. In winter it steams like a kettle.', 'I sat here the day the doctor\'s letter came. Words like "progressive" and "rest". I took the rest part seriously. Here I am.'] },
  { id: 'L31', site: 'treeFoot', title: 'Marks on the post', text: ['Go back up to the treehouse and look at the marks again.', 'The last mark is taller than me. I remember being surprised by that. Not by whose it was. Just by how tall.'] },
  { id: 'L32', site: 'lie1', title: 'The north hill', text: ['Lie here in summer and watch the clouds come in from the sea.', 'Someone and I had a fight that never ended. Not a loud one. A long one. The quiet kind is worse.'] },
  { id: 'L33', site: 'volcanoFire', title: 'Fire on the mountain', text: ['A fire on a volcano: you would think it was not needed. It still feels good.', 'From here you can see the home jetty. You can see whether anyone is waiting on it. No one has been, for a long time.'] },
  { id: 'L34', site: 'lavaHall', title: 'The lava chamber', text: ['The pond of fire under the mountain. Look, do not touch.', 'Everything here is still being made. The island is not finished. Neither are you.'] },
  { id: 'L35', site: 'cove', title: 'The hidden cove', text: ['You can only get here by boat. Nobody else knows about it.', 'I made a promise here once, to someone small: that I would always come when called. I did not keep it. Not the last time.'] },
  { id: 'L36', site: 'lhLanding', title: 'The steps', text: ['Ninety-one steps up the cleft. Count them if you like.', 'The radio in the lighthouse used to reach the mainland. I used to talk to someone every Sunday. Then every other Sunday. Then not at all.'] },
  { id: 'L37', site: 'wreck', title: 'The old boat', text: ['This boat will never sail again. I keep it anyway.', 'It had a name painted on the stern, once. It was a person\'s name. The paint is gone.'] },
  { id: 'L38', site: 'meadowSide', title: 'The wind', text: ['On Millholm the wind never stops. Let it blow through you.', 'Some days I can hear a voice in it, saying something with two syllables. A name. Too fast to catch.'] },
  { id: 'L39', site: 'pond', title: 'The pond', text: ['The frogs come back every spring, the same pond, the same stones.', 'They don\'t need to remember the way. They just go home. I envy them.'] },
  { id: 'L40', site: 'lie2', title: 'The glade', text: ['Lie on your back here and the spruce crowns make a ring round the sky.', 'I was a pilot, you know. Mail and people between the islands and the mainland. I could find my way anywhere in fog. Now I sometimes lose the way to the well.'] },
  { id: 'L41', site: 'signpost', title: 'The signpost', text: ['Cabin, jetty, benches. Signposts are a kindness to people who forget. I made these when I started to.', 'Somewhere there is a person for whom there is no signpost. You will have to find the way by heart.'] },
  { id: 'L42', site: 'jettyHead', title: 'The end of the jetty', text: ['Stand here at dusk and watch the water go dark.', 'I used to wave from here when a plane came in. A small figure would wave back from the window. It was the best feeling in the world.'] },
  { id: 'L43', site: 'palmJetty2', title: 'The other jetty', text: ['Two jetties on a small island. One for coming, one for going, someone said.', 'I have been going for a long time. Maybe it is time for coming.'] },
  { id: 'L44', site: 'marshJetty2', title: 'Mail', text: ['There were letters for me once, arriving with the boat every week. I kept them in the observatory, in the sea chest.', 'One had a photograph of a wedding. I did not go. I told myself the weather was bad. It was not.'] },
  { id: 'L45', site: 'emberBend', title: 'Halfway up', text: ['Halfway. Turn round and look back. You came all this way.', 'This is the letter where I tell you: you have a son. I cannot write his name. Every time I try, the pen stops. You will remember it yourself. You must.'] },
  { id: 'L46', site: 'marshSide', title: 'Stubborn', text: ['Herons are stubborn. They stand in the cold for hours to catch one fish.', 'He is stubborn too. He gets it from me. He also gets the habit of waiting for the other one to call first.'] },
  { id: 'L47', site: 'fire0', title: 'The beach fire', text: ['The fire by the jetty. The first one you can see coming in by boat.', 'He liked to light it. He was careful with matches long before he was careful with anything else.'] },
  { id: 'L48', site: 'lhPlateau', title: 'The far side of the rock', text: ['Nothing between you and the mainland here but water.', 'He is over there somewhere. A whole life I know almost nothing about. Children of his own, perhaps.'] },
  { id: 'L49', site: 'lie3', title: 'The south slope', text: ['From here the sea looks like it goes on forever. It doesn\'t. There is always a shore.', 'I started a letter to him on this slope. I could not finish it. It is the next one you will find.'] },
  { id: 'L50', site: 'boardwalk', title: 'Unfinished', text: ['"Dear —"', 'And then nothing. Half a page of nothing. I am sorry. Finish it for me, in your own voice, out loud, on the radio.'] },
  { id: 'L51', site: 'marshFire', title: 'The frequency', text: ['The lighthouse radio, once it works: turn the big dial to the mark scratched in the brass. That is his.', 'I scratched that mark the day he left for the mainland. He was nineteen. He said "call me". I said "you call me".'] },
  { id: 'L52', site: 'emberHigh', title: 'Nearly at the top', text: ['From up here you can see everything you have walked these years.', 'Every letter was a step on a path back to one person. You are almost there.'] },
  { id: 'L53', site: 'lie4', title: 'The west meadow', text: ['Lie with your feet to the sunset. Breathe.', 'Whatever happens on the radio, he will be glad you called. I am sure of very little now. I am sure of that.'] },
  { id: 'L54', site: 'palmFire', title: 'The last letter', text: ['This is the last one I hid.', 'If you have found it, then you have walked all of it: every island, every season, every year it took. You are not the person who wrote these. You are better. Go home. Call your son.'] },
  codeLetter(CODES[0], 'Millholm', 'The windmill\'s lock. I hid this where the millstones are, out of the wind.'),
  codeLetter(CODES[1], 'Palm Cay', 'The palm\'s lock. Inside the hut, where it is always summer.'),
  codeLetter(CODES[2], 'Ember Rock', 'The volcano\'s lock. In the observatory, under the turning dome.'),
  codeLetter(CODES[3], 'Heron Marsh', 'The heron\'s lock. In the lodge, where the old fisherman kept his rods.'),
  codeLetter(CODES[4], 'the lighthouse rock', 'The lighthouse lock. By the lighthouse door, where the wind is fiercest.'),
  codeLetter(CODES[5], 'the islet', 'The shell lock. On the islet, the smallest of them all, which still counts.'),
];

/** The flashbacks: placeholders for pictures (or short videos) to come. */
export const FLASHBACKS = [
  { id: 'fb01', title: 'A small hand', caption: 'A wooden jetty in summer. A small hand holding yours, very tight. Someone laughing at a seagull.', picture: 'A child\'s hand in an adult\'s, on a sunny jetty, seen from above; only hands and planks.' },
  { id: 'fb02', title: 'The kite', caption: 'A red kite over a meadow. A boy of six running, shouting "higher, higher".', picture: 'A red kite against a blue sky, a small boy running across a meadow below, seen from behind.' },
  { id: 'fb03', title: 'Seven candles', caption: 'A cake with seven candles. A paper crown that keeps slipping over one eye.', picture: 'A homemade cake with seven candles on a cabin table, a paper crown beside it.' },
  { id: 'fb04', title: 'The model plane', caption: 'Glue, balsa wood and a boy\'s tongue poking out in concentration at the kitchen table.', picture: 'Small hands assembling a balsa-wood floatplane model at a wooden table, lamp light.' },
  { id: 'fb05', title: 'Oil on his hands', caption: 'A young man in a mechanic\'s jacket by a seaplane, wiping oil from his hands, grinning: "She\'ll fly."', picture: 'A young man beside a red-and-cream floatplane at a jetty, rag in hand, face turned away.' },
  { id: 'fb06', title: 'The door', caption: 'Raised voices in a small kitchen. A teenager\'s back, walking out into the rain. The door left open.', picture: 'A cabin doorway open onto rain at night, a figure in a hood walking away down a path.' },
  { id: 'fb07', title: 'The Swan', caption: 'A boy on your shoulders under a sky full of stars. "That one is the Swan." "Which one?" "All of them."', picture: 'Silhouette of an adult with a child on their shoulders under a starry sky, the Milky Way overhead.' },
  { id: 'fb08', title: 'The corridor', caption: 'A hospital corridor. A doctor\'s voice, far away: "...memory... it may go in patches... somewhere quiet would be best."', picture: 'A long pale hospital corridor, out of focus, a window at the end.' },
  { id: 'fb09', title: 'The gown', caption: 'A graduation photograph arriving in the post. You were not in it. You were at sea that week. You were always at sea that week.', picture: 'A photograph lying on a doormat: a young man in a graduation gown, the face not shown.' },
  { id: 'fb10', title: 'The wedding', caption: 'A wedding photograph and a note: "We wish you had been there." You read it standing on the jetty, twice.', picture: 'A wedding photograph held in weathered hands, the sea behind, the couple\'s faces turned to each other.' },
  { id: 'fb11', title: 'The phone', caption: 'A telephone ringing in an empty hallway. You stand at the top of the stairs and let it ring.', picture: 'An old telephone on a hall table, light from a window, the receiver on its hook.' },
  { id: 'fb12', title: 'The message', caption: 'A voice on an answering machine: "Come and live with us. Please. The kids would love it." Then a long pause before he hangs up.', picture: 'An answering machine with a blinking red light on a shelf, dusk light.' },
  { id: 'fb13', title: 'The storm', caption: 'Black water over the bow. The boat on its side. A crack of light on your temple. Then sand, cold, and this island.', picture: 'A small sailboat heeled over in a storm at night, lightning on the horizon.' },
  { id: 'fb14', title: 'The blanket', caption: 'A baby asleep in a knitted blanket. A name stitched in the corner, in blue thread: TOMAS.', picture: 'Close-up of a knitted baby blanket with a name embroidered in blue thread in the corner.' },
  { id: 'fb15', title: 'Loud and clear', caption: 'A teenage boy at the lighthouse radio: "Can you hear me? Over." You, laughing at the other end: "Loud and clear."', picture: 'A teenager in headphones at an old radio set, the lighthouse window behind him.' },
  { id: 'fb16', title: 'The mark', caption: 'Your own hand scratching a line on a brass dial with a nail. "That\'s his. So I never have to look it up."', picture: 'A brass radio dial with a small scratched mark beside one number.' },
  { id: 'fb17', title: 'Asleep on the chart', caption: 'A boy of nine asleep in the boat\'s cabin, his hand on the chart, a pencil still in it.', picture: 'A child asleep at a chart table inside a small boat, a pencil in his hand.' },
  { id: 'fb18', title: 'Nineteen', caption: 'The home jetty. He is nineteen and leaving. "Call me." "You call me." Neither of you did, for years.', picture: 'Two figures at the end of a jetty at dawn, a packed bag between them, a boat waiting.' },
  { id: 'fb19', title: 'His children', caption: 'A photograph you never saw, only imagined: two small children on a beach, with his eyes.', picture: 'Two small children building a sandcastle on a beach, seen from a distance.' },
  { id: 'fb20', title: 'Tomas', caption: 'Everything at once, like the crystals in the lantern light. Tomas. Your son. Grown, with a family of his own. Waiting, all these years, for you to call first.', picture: 'A grown man standing at a window looking out to sea, a phone in his hand.' },
];

const C = (season, title, days) => ({ season, title, days: days.map(([say, tasks, flash]) => ({ say, tasks, flash })) });
/** Twenty chapters of ten days. Each day: [what you think as it begins, tasks, flashback shown on waking (optional)]. */
export const CHAPTERS = [
  C('winter', 'Waking', [
    ['Darkness. Cold. A bed you do not know, in a room you do not know. Not even your own name.', ['letter:L01', 'fire:fireplace|Light the fireplace']],
    ['Grey light. The cabin smells of old smoke. Somebody has been looking after this place. You, apparently.', ['letter:L02', 'add:stick:5|Fetch 5 sticks (the woodpiles always have some)']],
    ['Snow on the roof. Your hands know where the cups are before you do.', ['letter:L03', 'add:water:1|Draw a cup of water at the well']],
    ['You are hungry, which seems like a good sign. The body remembers how to be alive.', ['letter:L04', 'eat:1|Eat something']],
    ['The sun came up out of the sea this morning. You did not know it could do that.', ['sit:sunrise|Watch the day begin from the sunrise bench', 'letter:L05']],
    ['A beach, a jetty, a boat. Driftwood bleached like bone.', ['add:driftwood:3|Gather 3 pieces of driftwood', 'fire:pit-beach|Light the fire on the beach']],
    ['A ring of old stones on the hill. Someone wants you to lie down in it.', ['letter:L06', 'lie|Lie down in the stone ring']],
    ['There is a house in a tree. Of course there is.', ['letter:L07', 'visit:treehouse|Climb up to the treehouse']],
    ['The woods are quiet under snow. Your breath is the loudest thing.', ['letter:L08', 'fire:pit-forest|Light the fire in the woods']],
    ['Ten days. Something stirred in the night, like a hand reaching for yours.', ['letter:L09', 'sit:sunset|Watch the sun go down from the sunset bench'], 'fb01'],
  ]),
  C('spring', 'Thaw', [
    ['The snow is going. Green underneath, as if it had been waiting.', ['letter:L10', 'sow:2|Sow 2 garden plots']],
    ['Water for the seeds, water for you.', ['add:water:2|Draw 2 cups of water', 'visit:pond|Visit the pond']],
    ['The boat. You are a little afraid of it, and a little not.', ['sail:islet|Sail to the islet', 'letter:L11']],
    ['The tide leaves gifts on the north shore.', ['letter:L12', 'add:shell:5|Gather 5 shells']],
    ['Your hands know how to tie a hook. Strange, what stays.', ['add:fish:2|Catch 2 fish']],
    ['Fish over a fire. Somebody always said you burn everything.', ['letter:L13', 'add:cooked:1|Cook something over a fire']],
    ['The hill is hollow. Bring a light.', ['letter:L14', 'visit:caverns|Explore the caverns']],
    ['Crystals in the dark, flashing like thoughts.', ['letter:L15', 'visit:crystal|Find the crystal chamber']],
    ['Round pebbles on the south beach. Four bounces, never more.', ['letter:L16', 'add:pebble:4|Collect 4 pebbles']],
    ['A crooked tree, bent but not broken. You know how it feels.', ['letter:L17', 'sailRound|Sail all the way round the island'], 'fb02'],
  ]),
  C('summer', 'Long Light', [
    ['The lighthouse has been watching you all spring. Time to visit.', ['sail:lighthouse|Sail to the lighthouse rock', 'letter:L18']],
    ['From the top you can see every island at once.', ['visit:lighthouseTop|Climb to the lighthouse gallery']],
    ['A fire on the rock, with the sea all round.', ['fire:pit-isle-rock|Light the fire on the lighthouse rock', 'add:cooked:1|Cook something']],
    ['The garden is giving back more than you gave it.', ['add:harvest:1|Harvest something in the garden', 'eat:2|Eat twice today']],
    ['North, to the island with the windmill.', ['sail:millholm|Sail to Millholm', 'letter:L19']],
    ['Inside the windmill: the smell of flour and old wood.', ['visit:windmill|Go inside the windmill', 'letter:C1']],
    ['Sheep, walls, wind. A tent, once, here.', ['letter:L20', 'fire:pit-isle-meadow|Light the fire on Millholm']],
    ['A long day of fishing. The sea is generous in summer.', ['add:fish:3|Catch 3 fish']],
    ['The bridge, the berries, the warm boards.', ['letter:L21', 'add:berry:3|Pick 3 handfuls of berries']],
    ['Seven candles, somewhere in your head, and a paper crown.', ['lie|Lie in the stone ring and watch the sky', 'sit:sunset|Watch the sunset'], 'fb03'],
  ]),
  C('autumn', 'Harvest', [
    ['Apples. The old tree is heavy with them.', ['add:apple:6|Pick 6 apples']],
    ['Everything in the garden at once.', ['add:harvest:3|Harvest 3 crops', 'add:cooked:1|Cook something']],
    ['West, to the island that pretends to be in the south seas.', ['sail:palm|Sail to Palm Cay', 'letter:L22']],
    ['The hut on stilts. Somebody kept it swept.', ['visit:hut|Go inside the beach hut', 'letter:C2']],
    ['Nothing but sea to the west. Courage, a letter says.', ['letter:L23', 'fire:pit-isle-palm|Light the fire on Palm Cay']],
    ['Mushrooms after the rain.', ['add:mushroom:3|Find 3 boletes', 'add:cooked:1|Roast something']],
    ['A chest by the cabin with six rows of dials. And a reason.', ['letter:L24', 'visit:codeChest|Look at the chest with six dials by the cabin']],
    ['The smallest island still counts.', ['sail:islet|Sail to the islet', 'letter:C6']],
    ['The lighthouse again; its door has a secret.', ['sail:lighthouse|Sail to the lighthouse', 'letter:C5']],
    ['Balsa wood and glue and a tongue poking out. Who was that?', ['add:apple:4|Pick 4 more apples', 'sit:sunrise|Sit on the sunrise bench'], 'fb04'],
  ]),
  C('winter', 'Six Dials', [
    ['The marsh in winter: silver pools and patient herons.', ['sail:marsh|Sail to Heron Marsh', 'letter:L25']],
    ['The fisherman\'s lodge.', ['visit:lodge|Go inside the marsh lodge', 'letter:C4']],
    ['Cold fingers, warm fire.', ['fire:pit-isle-marsh|Light the fire on Heron Marsh', 'add:fish:2|Catch 2 fish']],
    ['Count the letters. Four codes of six.', ['fire:fireplace|Light the fireplace and rest', 'eat:1|Eat something warm']],
    ['South, to the black mountain.', ['sail:ember|Sail to Ember Rock', 'letter:L26']],
    ['The path zigzags up. Take it slowly.', ['visit:observatory|Climb to the observatory', 'letter:C3']],
    ['Six codes. Six rows. Your hands are shaking a little.', ['chest|Open the chest with six dials']],
    ['The fuel can is heavy and smells of summer engines.', ['fuel|Pour the fuel into the seaplane']],
    ['Your hands know this too. Throttle, rudder, lift.', ['fly:home|Take off and fly over the home island']],
    ['A young man by a seaplane, grinning with oil on his hands.', ['refuel|Refuel the seaplane at a jetty', 'fly:lighthouse|Fly over the lighthouse'], 'fb05'],
  ]),
  C('spring', 'Wings', [
    ['North by air. Twelve minutes by boat; two by plane.', ['fly:millholm|Fly to Millholm', 'dockPlane:meadow|Tie the seaplane up at Millholm']],
    ['From above, the islands are a family round a table.', ['letter:L27']],
    ['Turquoise water under the floats.', ['fly:palm|Fly to Palm Cay', 'letter:L28']],
    ['Herons lift off as you come in low.', ['fly:marsh|Fly to Heron Marsh', 'letter:L29']],
    ['Round the mountain and back.', ['fly:ember|Fly round Ember Rock', 'fly:lighthouse|Fly past the lighthouse']],
    ['The garden again; another year, the same carrots.', ['sow:3|Sow 3 garden plots', 'add:water:1|Draw water']],
    ['Warm water out of black rock.', ['visit:spring|Sit by the hot spring on Ember Rock', 'letter:L30']],
    ['Pebbles and cones, small and countable.', ['add:pebble:3|Collect 3 pebbles', 'add:cone:4|Collect 4 spruce cones']],
    ['Marks on a post, at three heights.', ['letter:L31', 'visit:treehouse|Climb up to the treehouse']],
    ['A door slamming. Rain. A back walking away.', ['letter:L32', 'sit:sunset|Watch the sunset'], 'fb06'],
  ]),
  C('summer', 'Stars', [
    ['The observatory has a bed. Stay the night up there.', ['sleep:observatory|Sleep in the observatory']],
    ['The telescope: the dials, the eyepiece, the dark.', ['telescope|Look through the telescope at night']],
    ['A fire on the mountain\'s shoulder.', ['fire:pit-isle-volcano|Light the fire on Ember Rock', 'letter:L33']],
    ['Under the mountain, a pond of fire.', ['visit:lavaHall|Go down to the lava chamber', 'letter:L34']],
    ['A cove nobody else knows. Only by boat.', ['sail:cove|Sail into the hidden cove on Ember Rock', 'letter:L35']],
    ['Another night of stars.', ['telescope|Look through the telescope again']],
    ['The sea is generous; so are you, today.', ['add:fish:3|Catch 3 fish', 'add:cooked:2|Cook 2 things']],
    ['Summer crops.', ['add:harvest:3|Harvest 3 crops']],
    ['Ninety-one steps up the cleft.', ['letter:L36', 'visit:lighthouseTop|Climb to the lighthouse gallery']],
    ['A boy on your shoulders, a sky full of swans.', ['telescope|Find the Swan through the telescope', 'lie|Lie in the stone ring'], 'fb07'],
  ]),
  C('autumn', 'Old Roads', [
    ['Baked apples, the smell of every autumn.', ['add:apple:5|Pick 5 apples', 'add:cooked:1|Bake an apple over a fire']],
    ['Down into the hill again.', ['visit:caverns|Walk the caverns', 'visit:crystal|Find the crystal chamber']],
    ['The woods smell of rain and mushrooms.', ['add:mushroom:4|Find 4 boletes']],
    ['A long flight, north and west.', ['fly:millholm|Fly over Millholm', 'fly:marsh|Fly over Heron Marsh']],
    ['An old boat on the islet with no name.', ['sail:islet|Sail to the islet', 'letter:L37']],
    ['The sea brings messages, if you look.', ['bottle|Find a message in a bottle']],
    ['Something small and old, hidden for you.', ['keepsake|Find a keepsake']],
    ['The windmill island in the wind.', ['letter:L38', 'fire:pit-isle-meadow|Light the fire on Millholm']],
    ['The last of the garden.', ['add:harvest:2|Harvest 2 crops', 'eat:2|Eat twice today']],
    ['A corridor, a doctor, a word: quiet.', ['letter:L39', 'visit:sunset|Walk to the sunset bench'], 'fb08'],
  ]),
  C('winter', 'Quiet', [
    ['Snow again. You know this cabin now.', ['fire:fireplace|Light the fireplace', 'sit:cabin|Sit on the bench under the cabin window']],
    ['Wood for the long nights.', ['add:stick:8|Fetch 8 sticks']],
    ['Water, bread, the small things.', ['add:water:1|Draw water', 'eat:1|Eat something']],
    ['The stones in the snow.', ['visit:stones|Walk to the stone ring', 'lie|Lie down in the stone ring']],
    ['The spruce crowns make a ring round the sky.', ['letter:L40', 'fire:pit-forest|Light the fire in the woods']],
    ['Fishing in the cold.', ['add:fish:2|Catch 2 fish']],
    ['Round the island, the long way.', ['sailRound|Sail all the way round the island']],
    ['From the top of the lighthouse the mainland is a grey line.', ['visit:lighthouseTop|Climb to the lighthouse gallery']],
    ['Signposts for people who forget.', ['letter:L41', 'visit:bridge|Cross the footbridge']],
    ['A graduation gown. You were at sea.', ['letter:L42', 'visit:jetty|Stand at the end of the jetty'], 'fb09'],
  ]),
  C('spring', 'Seeds', [
    ['Seeds into cold soil, on trust.', ['sow:4|Sow 4 garden plots']],
    ['Water, again and again.', ['add:water:2|Draw 2 cups of water']],
    ['West by air to the white sand.', ['fly:palm|Fly to Palm Cay', 'fire:pit-isle-palm|Light the fire on Palm Cay']],
    ['A bottle on the tide.', ['bottle|Find a message in a bottle']],
    ['Pebbles on the south beach.', ['add:pebble:5|Collect 5 pebbles', 'visit:southBeach|Walk the south beach']],
    ['One jetty for coming, one for going.', ['letter:L43', 'dockPlane:palm|Tie the seaplane up at Palm Cay']],
    ['Fuel for the long flights.', ['fly:lighthouse|Fly to the lighthouse', 'refuel|Refuel the seaplane']],
    ['Spring crops.', ['add:harvest:2|Harvest 2 crops']],
    ['Up the ladder, to the marks.', ['visit:treehouse|Climb up to the treehouse']],
    ['A wedding photograph. "We wish you had been there."', ['letter:L44', 'fly:marsh|Fly to Heron Marsh'], 'fb10'],
  ]),
  C('summer', 'Bottles', [
    ['The sea keeps writing to you.', ['bottle|Find a message in a bottle']],
    ['A long morning on the jetty with a line in the water.', ['add:fish:4|Catch 4 fish']],
    ['To the mountain by air.', ['fly:ember|Fly to Ember Rock', 'visit:observatory|Climb to the observatory']],
    ['Stars, and one more thing you remember about them.', ['telescope|Look through the telescope']],
    ['The hidden cove again.', ['sail:cove|Sail into the hidden cove']],
    ['A feast, for nobody in particular.', ['add:cooked:2|Cook 2 things']],
    ['Small treasures.', ['keepsake|Find a keepsake']],
    ['The fire under the mountain.', ['visit:lavaHall|Go down to the lava chamber']],
    ['Halfway up. Turn round. Look back.', ['letter:L45']],
    ['A phone ringing in an empty hallway.', ['sit:sunrise|Watch the sunrise', 'fire:pit-beach|Light the fire on the beach'], 'fb11'],
  ]),
  C('autumn', 'Keepsakes', [
    ['The apple tree, again, as if it remembered for you.', ['add:apple:6|Pick 6 apples']],
    ['Old things want to be found.', ['keepsake|Find a keepsake']],
    ['To the marsh by air, the herons lifting.', ['fly:marsh|Fly to Heron Marsh', 'visit:lodge|Go inside the lodge']],
    ['Mushrooms in the wet woods.', ['add:mushroom:3|Find 3 boletes']],
    ['Stubborn herons, stubborn people.', ['letter:L46']],
    ['The garden\'s last gift of the year.', ['add:harvest:3|Harvest 3 crops']],
    ['Into the hill.', ['visit:caverns|Walk the caverns']],
    ['A warm meal against the dark.', ['add:cooked:2|Cook 2 things']],
    ['Keepsakes on a shelf, a life in small things.', ['keepsake|Find a keepsake']],
    ['"Come and live with us. Please."', ['visit:sunset|Walk to the sunset bench', 'sit:sunset|Watch the sun go down'], 'fb12'],
  ]),
  C('winter', 'The Storm', [
    ['Winter, and with it a feeling you have been here before.', ['fire:fireplace|Light the fireplace']],
    ['The islet in the snow.', ['sail:islet|Sail to the islet']],
    ['Light the beach fire. The first one you see coming in.', ['letter:L47', 'fire:pit-beach|Light the beach fire']],
    ['Fish for the stove.', ['add:fish:2|Catch 2 fish']],
    ['Driftwood on the north shore, after the gales.', ['add:driftwood:4|Gather 4 pieces of driftwood', 'visit:northBeach|Walk the north beach']],
    ['Woodsmoke and quiet.', ['add:stick:6|Fetch 6 sticks', 'eat:1|Eat something warm']],
    ['Round the island, careful of the wind.', ['sailRound|Sail all the way round the island']],
    ['From the lighthouse top, the storm clouds out at sea.', ['visit:lighthouseTop|Climb to the lighthouse gallery']],
    ['The far side of the rock faces the mainland.', ['letter:L48']],
    ['Black water. A crack of light. Sand. This island.', ['sleep:cabin|Sleep in your own bed'], 'fb13'],
  ]),
  C('spring', 'Names', [
    ['A name is close, like a word on the tip of your tongue.', ['sow:4|Sow 4 garden plots']],
    ['Water and green shoots.', ['add:water:2|Draw 2 cups of water', 'visit:garden|Walk round the garden']],
    ['The south slope, an unfinished letter.', ['letter:L49']],
    ['North by air, into the wind.', ['fly:millholm|Fly to Millholm', 'visit:windmill|Go inside the windmill']],
    ['The boardwalk over the marsh.', ['fly:marsh|Fly to Heron Marsh', 'letter:L50']],
    ['A bottle with someone else\'s words.', ['bottle|Find a message in a bottle']],
    ['Cones and pebbles; counting helps.', ['add:cone:5|Collect 5 spruce cones']],
    ['West by air.', ['fly:palm|Fly to Palm Cay']],
    ['The crooked tree, still standing.', ['visit:crooked|Visit the crooked tree']],
    ['A blanket, a name in blue thread.', ['visit:bed|Go to your bed and rest', 'sleep:cabin|Sleep in your own bed'], 'fb14'],
  ]),
  C('summer', 'The Radio', [
    ['The radio in the lighthouse. You remember it now: it is broken.', ['visit:lighthouseRadio|Find the old radio in the lighthouse']],
    ['A radio needs a valve. The windmill has a box of spares.', ['add:radioValve:1|Find a radio valve inside the windmill']],
    ['And a coil of copper wire. The fisherman had one.', ['add:copperCoil:1|Find a copper coil in the marsh lodge']],
    ['And an aerial wire.', ['add:aerialWire:1|Find aerial wire in the beach hut']],
    ['And a battery to wake it up.', ['add:battery:1|Find a battery in the observatory']],
    ['Valve, coil, wire, battery. Your hands remember the soldering iron.', ['radio:fix|Mend the radio in the lighthouse']],
    ['The radio hums. Nobody to call yet.', ['add:fish:3|Catch 3 fish']],
    ['Summer crops.', ['add:harvest:3|Harvest 3 crops']],
    ['Stars over the observatory.', ['telescope|Look through the telescope']],
    ['"Can you hear me? Over." "Loud and clear."', ['radio:listen|Listen to the radio in the lighthouse'], 'fb15'],
  ]),
  C('autumn', 'Frequencies', [
    ['Voices from the mainland, weather and ships.', ['radio:listen|Listen to the radio']],
    ['Apples, again.', ['add:apple:5|Pick 5 apples']],
    ['To the mountain.', ['fly:ember|Fly to Ember Rock', 'visit:spring|Sit by the hot spring']],
    ['A fishing boat calling for its harbour.', ['radio:listen|Listen to the radio']],
    ['A meal to steady the hands.', ['add:cooked:2|Cook 2 things']],
    ['A mark scratched in brass.', ['letter:L51', 'fire:pit-isle-marsh|Light the fire on Heron Marsh']],
    ['Mushrooms in the rain.', ['add:mushroom:3|Find 3 boletes']],
    ['Static, and under it, almost a voice.', ['radio:listen|Listen to the radio']],
    ['The last crops before the frost.', ['add:harvest:2|Harvest 2 crops']],
    ['A nail on brass: "That\'s his."', ['visit:lighthouseTop|Climb to the lighthouse gallery'], 'fb16'],
  ]),
  C('winter', 'Courage', [
    ['The radio is ready. You are not.', ['fire:fireplace|Light the fireplace']],
    ['Nearly at the top of the mountain.', ['letter:L52']],
    ['Round the island, to think.', ['sailRound|Sail all the way round the island']],
    ['The west meadow, feet to the sunset.', ['letter:L53', 'lie|Lie down in the stone ring']],
    ['To the lighthouse by air, and back.', ['fly:lighthouse|Fly to the lighthouse', 'refuel|Refuel the seaplane']],
    ['The last letter, on the holiday island.', ['fly:palm|Fly to Palm Cay', 'letter:L54']],
    ['Fish, fire, food.', ['add:fish:2|Catch 2 fish', 'add:cooked:1|Cook something']],
    ['The treehouse marks, one more time.', ['visit:treehouse|Climb up to the treehouse']],
    ['Wood for the last of the winter.', ['add:stick:6|Fetch 6 sticks']],
    ['A boy asleep on the chart, pencil in hand.', ['visit:jetty|Stand at the end of the jetty'], 'fb17'],
  ]),
  C('spring', 'Remembering', [
    ['It is coming back, in pieces, then in rooms.', ['sow:3|Sow 3 garden plots']],
    ['"Call me." "You call me."', ['visit:jetty|Stand at the end of the jetty'], 'fb18'],
    ['Places he loved: the treehouse.', ['visit:treehouse|Climb up to the treehouse']],
    ['Places he loved: the crooked tree.', ['visit:crooked|Visit the crooked tree']],
    ['Places he loved: the islet, which counts.', ['sail:islet|Sail to the islet']],
    ['Children with his eyes, on a beach you have never seen.', ['visit:southBeach|Walk the south beach'], 'fb19'],
    ['Places he loved: Palm Cay, where he learned to swim.', ['fly:palm|Fly to Palm Cay']],
    ['Places he loved: the stars.', ['telescope|Look through the telescope']],
    ['You practise the first words out loud, on the sunrise bench.', ['sit:sunrise|Sit on the sunrise bench']],
    ['Everything at once.', ['visit:lighthouseTop|Climb to the lighthouse gallery'], 'fb20'],
  ]),
  C('summer', 'The Call', [
    ['Today. The lighthouse. The brass mark.', ['visit:lighthouseRadio|Go to the radio in the lighthouse']],
    ['Your hands are steady. Your voice is not.', ['radio:call|Call Tomas on the radio']],
    ['"I\'ll come. Give me a little time to sort things." He is coming.', ['fire:fireplace|Light the fireplace', 'visit:porch|Sweep the cabin steps']],
    ['The garden should look its best.', ['add:harvest:3|Harvest 3 crops']],
    ['Fish for a guest.', ['add:fish:3|Catch 3 fish']],
    ['The boat should be ready, in case.', ['sailRound|Sail all the way round the island']],
    ['Fuel for the plane, to show him the islands.', ['refuel|Refuel the seaplane']],
    ['The keepsakes on the shelf, dusted.', ['keepsake|Find a keepsake']],
    ['A quiet evening on the sunset bench.', ['sit:sunset|Watch the sunset']],
    ['The radio crackles: "Soon. Autumn. Love you."', ['radio:listen|Listen to the radio']],
  ]),
  C('autumn', 'Homecoming', [
    ['Apples, the first thing he will smell.', ['add:apple:6|Pick 6 apples']],
    ['A table full of food.', ['add:cooked:3|Cook 3 things']],
    ['The last of the garden, for him.', ['add:harvest:3|Harvest 3 crops']],
    ['The beach fire, the first one you see coming in.', ['fire:pit-beach|Light the beach fire']],
    ['The radio: "Leaving the mainland tomorrow morning."', ['radio:listen|Listen to the radio']],
    ['One last flight round the islands, to say thank you.', ['fly:millholm|Fly over Millholm', 'fly:ember|Fly over Ember Rock', 'fly:marsh|Fly over Heron Marsh']],
    ['Fish for supper, for two.', ['add:fish:3|Catch 3 fish']],
    ['The sun comes up out of the sea, right over the lighthouse.', ['sit:sunrise|Watch the sunrise']],
    ['Your own bed. Tomorrow.', ['sleep:cabin|Sleep in your own bed']],
    ['A sound in the sky, from the east.', ['wait|Wait at the end of the home jetty']],
  ]),
];
export const STORY_DAYS = CHAPTERS.length * 10;
